### ISSUE TITLE
react and react-dom should be peer-dependencies

### ISSUE THREAD

**Issue by Nouzbe** [xiabingwu/dragm#4]
`react` and `react-dom` currently are dependencies. As a project using `dragm`, this leads to having several instances of these modules. They should be required as peer-dependencies.

**Comment by xiabingwu** [comment]
Thanks for your reminding，I fixed it @Nouzbe

**Comment by Nouzbe** [comment]
Thanks for the quick fix @xiabingwu. Would it be possible to change `react` and `react-dom` versions too, so that they are inline with [the ones required by Ant Design](https://github.com/ant-design/ant-design/blob/master/package.json#L38)?

Do you plan on releasing a new version with this fix soon?

**Comment by xiabingwu** [comment]
I released a new version,dragm@0.0.5 is inline with  Ant Design @Nouzbe
